--- #
- hosts: webservers
  user: ansible
  become: true
  connection: ssh
  tasks:
    - name: installing httpd in webservers
      action: yum name=httpd state=present
      notify: start httpd service

  handlers:
    - name: start httpd service
      action: service name=httpd state=started


