--- # installing java and tomcat
- hosts: webservers
  become: yes

  tasks:
    - name: installing java on redhat
      yum: name=java state=present
      when: ansible_os_family == "RedHat"

    - name: installing java on debian
      apt: name=java state=present
      when: ansible_os_family == "debian"

    - name: download tomcat package
      get_url: url=https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.77/bin/apache-tomcat-8.5.77.tar.gz dest=/opt
     
    - name:
      unarchive:
      src: /opt//apache-tomcat-8.5.77.tar.gz
      dest: /opt
      remote_src: yes




    


