--- # installations 
- name: this is test playbook
  hosts: webservers
  become: yes
  user: ansible
  connection: ssh
    
  tasks:
    - name: installing httpd in webservers
      action: yum name=httpd state=installed
      notify: start httpd service

  handlers:
    - name: start httpd service
      action: service name=httpd state=started
