--- #
- name: installing multiple packages
  hosts: webservers
  become: true
  tasks:
    - name: installing packages
      yum:
        name: ['git','tree','java','docker','mysql']
        state: installed

